name: Maven Build, Dockerize, and Deploy to Minikube

on:
  #push:
  #  branches:
  #    - main  # Trigger workflow on push to the 'main' branch
  workflow_dispatch:
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Maven Project
      run: mvn clean package

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-artifact
        path: target/*.jar

  build-docker:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: spring-boot-artifact

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest

  deploy-minikube:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        sudo minikube start --driver=docker
        sudo minikube kubectl -- get po -A

    - name: Deploy to Minikube using YAML files
      run: |
        # Update image in deployment.yaml
        sed -i "s|<DOCKER_IMAGE>|${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest|g" deployment.yaml

        # Apply deployment and service configurations
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

        # Verify deployment
        kubectl get all
